### ISSUE TITLE
Add requirements.txt to the project

### ISSUE THREAD

**Issue by stejans** [brucemack/nanovna-controller#1]
Hi Bruce,

I would appreciate if you could add a requirements.txt to the repository. this would list all required packages along with the version numbers you use and could easily re-create the same setup on any machine with pip install -r requirements.txt.

Regards,
Stefan, DK7STJ

**Comment by brucemack** [comment]
Done.  Thanks for the suggestion Stefan, I never knew about that convention.  I’m a Python newbie.  

73s, Bruce KC1FSZ

**Comment by brucemack** [comment]
Done
